### ISSUE TITLE
Bug in Tucker Decomposition

### ISSUE THREAD

**Issue by wavefunction91** [ValeevGroup/BTAS#110]
The use of row major `LAPACKE_dsyev` in the [the Tucker decomposition](https://github.com/BTAS/BTAS/blob/master/btas/generic/tucker.h#L46) yields incorrect results for linear algebra stacks based on LAPACKE < v3.9.0 (including MKL). This bug in LAPACKE was fixed in [this commit](https://github.com/Reference-LAPACK/lapack/commit/7d5bb9e5e641772227022689162dd9cc47e64de0#diff-013e9b279c18a3251d56dccbbb6c2121bf77e4277877640c08932199fb0a8f26L75) in NETLIB LAPACK(E) (released in v3.9.0), not sure if its been propagated to MKL, etc (ping @jeffhammond)

For example, the [RALS Tucker + CP UT](https://github.com/BTAS/BTAS/blob/master/unittest/tensor_cp_test.cc#L179) has an input Grammian
```
5.68567, 3.59239, 3.35448, 3.87387, 4.59174, 
3.59239, 7.41165, 4.35048, 5.19847, 4.88456, 
3.35448, 4.35048, 6.14408, 4.16873, 4.25541, 
3.87387, 5.19847, 4.16873, 6.01514, 3.77859,
4.59174, 4.88456, 4.25541, 3.77859, 5.81851,
```

LAPACKE provides the correct eigenvalues
```
1.89885
2.38082
3.15313
23.1348
```

but incorrect eigenvectors (GCC 8.3.0 + MKL 2019.3.199 + GNU Thread, due to the use of a [symmetric copy](https://github.com/Reference-LAPACK/lapack/commit/7d5bb9e5e641772227022689162dd9cc47e64de0#diff-013e9b279c18a3251d56dccbbb6c2121bf77e4277877640c08932199fb0a8f26L75) for the eigenvectors in LAPACKE):
```
-0.472845,  3.59239,   3.35448,   3.87387,   4.59174,
-0.389004,  0.401774,  4.35048,   5.19847,   4.88456,
-0.21024,  -0.035183,  0.871314,  4.16873,   4.25541,
 0.424681, -0.708451, -0.180977, -0.291731,  3.77859,
 0.632881,  0.51977,  -0.0073491, 0.35477,  -0.450982,
```

Note that the correct eigenvectors are (up to a sign)
```
 0.472845,  0.255492,  0.241504,  -0.700085, 0.403359,
 0.389004, -0.401774,  0.386886,   0.537119, 0.499075, 
 0.21024,   0.035183, -0.871314,   0.102053, 0.430068, 
-0.424681,  0.708451,  0.180977,   0.291731, 0.447083,
-0.632881, -0.51977,   0.0073491, -0.35477,  0.450982,
```

Note that this is no longer a problem in https://github.com/BTAS/BTAS/pull/109 due to removal of LAPACKE interfaces in BTAS

**Comment by evaleev** [comment]
Closed via #109
